#!/bin/bash

# this script starts the test project (django server) and runs specified test (or all).



SCRIPT_DIR=$(dirname $0)

cd $SCRIPT_DIR

if [ "$PYTHONPATH" != "" ]; then
    PYTHONPATH="$PYTHONPATH:src"
else
    PYTHONPATH="src"
fi

export PYTHONPATH=$PYTHONPATH

export DJANGO_SETTINGS_MODULE="testproject.settings"



function django_is_up() {
    wget -q -O /dev/null "http://localhost:8000/"
}

function wait_until_django_up() {
    echo "Waiting for django to come up..."
    until django_is_up; do sleep 0.2; done
    echo "django found. Continuing..."
}


# launch local django dev server
cd src/testproject
python manage.py runserver > /dev/null 2>&1 &
wait_until_django_up
cd -

# run the test(s)
echo
python src/runtests.py "$@"

# kill django dev server
kill $(ps aux | grep '[p]ython manage.py' | awk '{print $2}')


