#! /bin/bash


SCRIPT_DIR=$(dirname $0)

cd $SCRIPT_DIR

if [ "$PYTHONPATH" != "" ]; then
    PYTHONPATH="$PYTHONPATH:src"
else
    PYTHONPATH="src"
fi
export PYTHONPATH=$PYTHONPATH


export DJANGO_SETTINGS_MODULE="testproject.settings"


function django_is_up() {
    wget -q -O /dev/null "http://localhost:8000/"
}

function wait_until_django_up() {
    echo "Waiting for django to come up..."
    until django_is_up; do sleep 0.2; done
    echo "django found. Continuing..."
}

java -jar selenium-server-standalone-2.0a7.jar -trustAllSSLCertificates &
selenium_pid=$!

sleep 5

cd src/testproject
python manage.py runserver &
wait_until_django_up
cd -

python src/runtests.py "$@"

kill $selenium_pid
kill $(ps aux | grep '[p]ython manage.py' | awk '{print $2}')


