#!/usr/bin/env python

from os.path import dirname, join
from sys import path


if __name__ == "__main__":
    path.insert(0, join(dirname(__file__), "src"))
    from sst.scripts import remote
    remote.main()
