#!/usr/bin/env python
#
#   Copyright (c) 2011 Canonical Ltd.
#
#   This file is part of: SST (selenium-simple-test)
#   https://launchpad.net/selenium-simple-test
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#


import os
import subprocess
import sys
import time
import urllib

try:
    # installed
    import sst
except ImportError:
    # from the development directory
    this_dir = os.path.abspath(os.path.dirname(__file__))
    sys.path.append(os.path.join(this_dir, 'src'))
    import sst

from sst.command import get_run_options, clear_old_results


def main():
    (cmd_opts, args) = get_opts()

    clear_old_results()

    if cmd_opts.quiet:
        from sst import actions
        actions.VERBOSE = False

    if cmd_opts.xserver_headless:
        from pyvirtualdisplay import Display
        print '\nstarting virtual display...'
        display = Display(visible=0, size=(1024, 768))
        display.start()

    if cmd_opts.run_tests:
        cmd_opts.dir_name = 'selftests'
        run_django()

    print '----------------------------------------------------------------------'

    sst.runtests(
        args,
        test_dir=cmd_opts.dir_name,
        report_format=cmd_opts.report_format,
        browser_type=cmd_opts.browser_type,
        javascript_disabled=cmd_opts.javascript_disabled,
        shared_directory=cmd_opts.shared_modules,
        screenshots_on=cmd_opts.screenshots_on,
        failfast=cmd_opts.failfast,
        debug=cmd_opts.debug,
    )

    print '----------------------------------------------------------------------'

    if cmd_opts.run_tests:
        print '\nkilling django...'
        kill_django()
        
    if cmd_opts.xserver_headless:
        print '\nstopping virtual display...\n'
        display.stop()



def run_django():
    subprocess.Popen(['./src/testproject/manage.py', 'runserver'],
        stderr=open(os.devnull, 'w'),
        stdout=open(os.devnull, 'w')
        )
    print '----------------------------------------------------------------------'
    print 'waiting for django to come up...'
    while True:
        try:
            resp = urllib.urlopen('http://localhost:8000/')
            if resp.code == 200:
                break
        except IOError:
            time.sleep(0.2)
    print 'django found. continuing...'
    return



def kill_django():
    try:
        urllib.urlopen('http://localhost:8000/kill_django')
    except IOError:
        pass



def get_opts():
    parser = get_run_options()
    (cmd_opts, args) = parser.parse_args()
    return (cmd_opts, args)



if __name__ == '__main__':
    main()
