#! /bin/bash

SCRIPT_DIR=$(dirname $0)

cd $SCRIPT_DIR

java -jar ../selenium-server-standalone-2.0a7.jar -trustAllSSLCertificates &
selenium_pid=$!

python ../src/runtests.py "$@"

kill $selenium_pid
