#! /bin/bash

SCRIPT_DIR=$(dirname $0)

cd $SCRIPT_DIR

java -jar ../selenium-server-standalone-2.0b1.jar -trustAllSSLCertificates &>selenium.log &
selenium_pid=$!

python ../src/runtests.py "$@"

kill $selenium_pid
